id: I56A1599B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T18:34:25+00:00'
last_modified: '2022-06-08T13:44:49.698837+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4769
  title: སྡེ་དགེ་པར་ཁང་དང་དཔལ་སྤུངས་དགོན་དུ་བཞུགས་པའི་ཤིང་པར་རྣམས་ཀྱི་དབུ་ཤོག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '4763':
      image_group_id: I1KG4819
      title: ''
      total_pages: 2238
      order: 1
      base_file: 4763.txt
    FF22:
      image_group_id: I1KG4820
      title: ''
      total_pages: 3348
      order: 2
      base_file: FF22.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
