id: P010457
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-19 20:50:52.091461
source_metadata:
  id: bdr:W1KG4769
  title: སྡེ་དགེ་པར་ཁང་དང་དཔལ་སྤུངས་དགོན་དུ་བཞུགས་པའི་ཤིང་པར་རྣམས་ཀྱི་དབུ་ཤོག
  author: ''
  volumes:
    b57a8e2a22de4ca39f50fd99fabf25f4:
      image_group_id: I1KG4819
      title: ''
      volume_number: 1
      total_pages: 2238
      base_file: v001.txt
    37a12dab553445af9348f67abb537a40:
      image_group_id: I1KG4820
      title: ''
      volume_number: 2
      total_pages: 3348
      base_file: v002.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
